### ISSUE TITLE
[vscode-apollo] Changing service in `apollo.config.js` requires a full VSCode restart

### ISSUE THREAD

**Issue by justinanastos** [apollographql/apollo-tooling#987]
If you change the service name in `apollo.config.js` (and the corresponding API key in in `.env`), VSCode will report errors until you quit and re-open. It appears as though the schema is being fetched for the original service; I see this in an error message but don't want to paste a screenshot here because it's sensitive.

**Comment by JakeDawkins** [comment]
This should be fixed with #897 🎉

**Comment by justinanastos** [comment]
Thank you @JakeDawkins !

**Comment by iki** [comment]
Please reopen, the extension still does not reflect `localSchemaFile` change until VSCode restart.

Tested in current version `2.21.0`.

See the original report https://github.com/apollographql/apollo-tooling/issues/669#issuecomment-484400735 by @kazinad.
